### ISSUE TITLE
[BE] 프로젝트 셋업

### ISSUE THREAD

**Issue by d0lim** [TEAM-LEG3ND/luwak#13]
BE 프로젝트 셋업 부탁드립니다~

선택한 기술 스택 등 내용들 Comment로 남겨주시면 감사하겠습니다.

최근 진행하시던 분으로 Assignee 드렸습니다.

완료 되면 Issue Close 및 Projects 에서 상태 Done 으로 변경 부탁드립니다.

**Comment by d0lim** [comment]
@redjen8 @ammerss

**Comment by redjen8** [comment]
### 프로젝트 기술 스택 정의

- NestJS
- PostgreSQL
- TypeORM
- minio (이미지 저장 용)
- redis (싱글 노드)
